# ============================================================
# eod_simulator/simulator.py — Daily EOD Paper Trade Checker
# ============================================================
# Run this every market close (~3:30 PM IST) to check:
#   "Would the algo have traded today? What was the outcome?"
#
# Extracted from Cell 12 notebook logic.
#
# Usage:
#   python eod_simulator/simulator.py
#
#   Or from Jupyter/Colab:
#   from eod_simulator.simulator import check_today, log_result, show_week_summary
#   signal = check_today(groww, strategy='gap_fill', instrument='BANKNIFTY')
#   log_result(signal, actual_pnl=None)   # actual_pnl if manually traded
#   show_week_summary()
#
# Input:
#   - Today's OHLCV from Groww (1-min or 15-min, last candle)
#   - market_signal_YYYY-MM-DD.json from daily_report/ (optional macro context)
#
# Output:
#   - Printed signal for today
#   - Appended row in paper_trades.csv
# ============================================================

import os
import json
import pandas as pd
from datetime import date, datetime


# ── Config ────────────────────────────────────────────────────────────────────
PAPER_TRADES_CSV = os.path.join(
    os.path.dirname(os.path.dirname(__file__)), 'paper_trades.csv'
)
SIGNAL_DIR = os.path.join(
    os.path.dirname(os.path.dirname(__file__)), 'daily_report'
)


def _load_today_signal_json(today: date = None) -> dict:
    """
    Load today's market signal JSON if it exists.
    Generated by the 7:30 AM daily_report cron.
    """
    if today is None:
        today = date.today()
    fname = os.path.join(SIGNAL_DIR, f"market_signal_{today}.json")
    if os.path.exists(fname):
        with open(fname) as f:
            return json.load(f)
    return {}


def check_today(groww,
                strategy: str = 'gap_fill',
                instrument: str = 'BANKNIFTY',
                today: date = None) -> dict:
    """
    Fetch today's data and determine if the strategy would have traded.

    Args:
        groww      : Authenticated GrowwAPI instance
        strategy   : Strategy name — 'gap_fill', 'orb', or 'vwap_reversion'
        instrument : Instrument key — 'BANKNIFTY' or 'NIFTY'
        today      : Date to check (defaults to today)

    Returns:
        dict: Signal with keys:
            date, strategy, instrument, traded (bool),
            direction, entry, target, stop, bias_score,
            macro_ok, gap_pts, signal_confidence,
            notes
    """
    from config import INSTRUMENTS, STRATEGIES, MACRO
    from data.fetch import fetch_instrument

    if today is None:
        today = date.today()

    signal = {
        'date':             str(today),
        'strategy':         strategy,
        'instrument':       instrument,
        'traded':           False,
        'direction':        None,
        'entry':            None,
        'target':           None,
        'stop':             None,
        'bias_score':       0.0,
        'macro_ok':         True,
        'gap_pts':          0.0,
        'signal_confidence': 0,
        'notes':            '',
    }

    instr_cfg      = INSTRUMENTS[instrument]
    strategy_cfg   = STRATEGIES[strategy]
    strategy_params = strategy_cfg['params']

    # ── Fetch last 20 trading days for ATR context ────────────────────────────
    from datetime import timedelta
    lookback = (today - timedelta(days=30)).strftime('%Y-%m-%d')
    end      = (today + timedelta(days=1)).strftime('%Y-%m-%d')

    try:
        data = fetch_instrument(instrument, lookback, end, groww=groww)
    except Exception as e:
        signal['notes'] = f"Data fetch failed: {e}"
        return signal

    if data.empty:
        signal['notes'] = 'No data available'
        return signal

    # ── Load macro signal from morning JSON ───────────────────────────────────
    morning_signal = _load_today_signal_json(today)
    if morning_signal:
        macro_filters = morning_signal.get('macro_filters', {})
        signal['macro_ok'] = macro_filters.get('all_pass', True)
        if not signal['macro_ok']:
            signal['notes'] = (
                f"Macro blocked: "
                f"VIX={macro_filters.get('vix_status', '?')} | "
                f"S&P={macro_filters.get('sp_status', '?')} | "
                f"FII={macro_filters.get('fii_status', '?')}"
            )
            return signal

    # ── Run strategy on today's data ──────────────────────────────────────────
    import importlib
    module = importlib.import_module(strategy_cfg['module'])
    run_fn = getattr(module, strategy_cfg['function'])

    try:
        if strategy == 'gap_fill':
            trade_log = run_fn(data, instr_cfg, strategy_params)
        else:
            trade_log = run_fn(data, instr_cfg, strategy_params)
    except Exception as e:
        signal['notes'] = f"Strategy run failed: {e}"
        return signal

    # Find today's trade if it exists
    if not trade_log.empty:
        today_trades = trade_log[pd.to_datetime(trade_log['date']).dt.date == today]
        if not today_trades.empty:
            row = today_trades.iloc[0]
            signal.update({
                'traded':            True,
                'direction':         row.get('direction'),
                'entry':             row.get('entry'),
                'target':            row.get('target'),
                'stop':              row.get('stop'),
                'bias_score':        row.get('bias_score', 0.0),
                'gap_pts':           row.get('gap_pts', 0.0),
                'pnl_pts':           row.get('pnl_pts'),
                'pnl_rs':            row.get('pnl_rs'),
                'exit_reason':       row.get('exit_reason'),
                'signal_confidence': int(round(row.get('bias_score', 0.0) * 10)),
            })
        else:
            signal['notes'] = 'No setup today (gap outside range or no reversion)'
    else:
        signal['notes'] = 'No trades in result'

    return signal


def log_result(signal: dict, actual_pnl: float = None) -> None:
    """
    Append today's signal and outcome to paper_trades.csv.

    Args:
        signal     : dict from check_today()
        actual_pnl : If manually traded, override the simulated P&L (₹)
    """
    row = {
        'date':             signal.get('date', str(date.today())),
        'strategy':         signal.get('strategy'),
        'instrument':       signal.get('instrument'),
        'traded':           signal.get('traded', False),
        'direction':        signal.get('direction'),
        'entry':            signal.get('entry'),
        'target':           signal.get('target'),
        'stop':             signal.get('stop'),
        'bias_score':       signal.get('bias_score'),
        'macro_ok':         signal.get('macro_ok', True),
        'gap_pts':          signal.get('gap_pts'),
        'pnl_pts':          signal.get('pnl_pts'),
        'pnl_rs_simulated': signal.get('pnl_rs'),
        'pnl_rs_actual':    actual_pnl,
        'exit_reason':      signal.get('exit_reason'),
        'signal_confidence': signal.get('signal_confidence'),
        'notes':            signal.get('notes', ''),
        'logged_at':        datetime.now().strftime('%Y-%m-%d %H:%M'),
    }

    df_new = pd.DataFrame([row])

    if os.path.exists(PAPER_TRADES_CSV):
        df_existing = pd.read_csv(PAPER_TRADES_CSV)
        # Avoid duplicate entries for the same date + strategy
        mask = (
            (df_existing['date'] == row['date']) &
            (df_existing['strategy'] == row['strategy']) &
            (df_existing['instrument'] == row['instrument'])
        )
        df_existing = df_existing[~mask]
        df_out = pd.concat([df_existing, df_new], ignore_index=True)
    else:
        df_out = df_new

    df_out.to_csv(PAPER_TRADES_CSV, index=False)
    pnl_str = f"₹{row['pnl_rs_actual']:,.0f}" if actual_pnl is not None \
              else f"sim ₹{row['pnl_rs_simulated']:,.0f}" if row['pnl_rs_simulated'] else 'no trade'
    print(f"  📝 Logged: {row['date']} | {row['strategy']} | "
          f"{row['direction'] or 'NO TRADE'} | {pnl_str}")


def show_week_summary(lookback_days: int = 7) -> None:
    """
    Print a summary of the last N days from paper_trades.csv.
    """
    if not os.path.exists(PAPER_TRADES_CSV):
        print("No paper trades logged yet.")
        return

    df = pd.read_csv(PAPER_TRADES_CSV)
    df['date'] = pd.to_datetime(df['date'])
    cutoff = pd.Timestamp.today() - pd.Timedelta(days=lookback_days)
    recent = df[df['date'] >= cutoff].sort_values('date')

    if recent.empty:
        print(f"No paper trades in the last {lookback_days} days.")
        return

    print(f"\n{'='*55}")
    print(f"  PAPER TRADE SUMMARY — Last {lookback_days} days")
    print(f"{'='*55}")
    print(f"  {'Date':<12} {'Strategy':<12} {'Dir':<6} {'SimP&L':>10} {'ActP&L':>10} {'Signal':>7}")
    print(f"  {'-'*60}")

    sim_total = 0.0
    act_total = 0.0

    for _, row in recent.iterrows():
        sim = row.get('pnl_rs_simulated', 0) or 0
        act = row.get('pnl_rs_actual', 0) or 0
        conf= row.get('signal_confidence', 0) or 0
        sim_total += sim
        act_total += act
        direction  = row.get('direction', 'NO TRADE') or 'NO TRADE'
        sim_str    = f"₹{sim:>8,.0f}" if sim else '        —'
        act_str    = f"₹{act:>8,.0f}" if act else '        —'
        print(f"  {str(row['date'].date()):<12} "
              f"{str(row.get('strategy','')):<12} "
              f"{direction:<6} "
              f"{sim_str}  {act_str}  {conf:>5}/10")

    print(f"  {'-'*60}")
    print(f"  {'TOTAL':<12} {'':12} {'':6} "
          f"₹{sim_total:>8,.0f}  ₹{act_total:>8,.0f}")

    traded = recent[recent['traded'] == True]
    if not traded.empty:
        print(f"\n  Traded days   : {len(traded)}/{len(recent)}")
        wins = (traded['pnl_rs_simulated'] > 0).sum()
        print(f"  Win rate (sim): {wins}/{len(traded)} = "
              f"{wins/len(traded)*100:.1f}%")


# ── CLI entry point ───────────────────────────────────────────────────────────
if __name__ == '__main__':
    print("EOD Simulator — run check_today() with a GrowwAPI instance.")
    print("Example:")
    print("  from eod_simulator.simulator import check_today, log_result")
    print("  signal = check_today(groww, strategy='gap_fill', instrument='BANKNIFTY')")
    print("  log_result(signal)")
    show_week_summary()
